### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by hdarwin** [binjitsu/binjitsu#70]
in my case ctypes.sizeof(elf_prstatus_amd64) is 0x14c. what's wrong?
```
root@ubuntu:~# uname -a
Linux ubuntu 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 14:46:51 UTC 2015 i686 i686 i686 GNU/Linux
root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
root@ubuntu:~# python -m pwn
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwn/__init__.py", line 2, in <module>
    from .toplevel import *
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwn/toplevel.py", line 17, in <module>
    import pwnlib
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwnlib/__init__.py", line 37, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwnlib/dynelf.py", line 54, in <module>
    from . import elf
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwnlib/elf/__init__.py", line 2, in <module>
    from .corefile import Core
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwnlib/elf/corefile.py", line 11, in <module>
    from .datatypes import *
  File "/usr/local/lib/python2.7/dist-packages/binjitsu-2.2.1-py2.7.egg/pwnlib/elf/datatypes.py", line 544, in <module>
    assert ctypes.sizeof(elf_prstatus_amd64) == 0x150
AssertionError
```

**Comment by zachriggle** [comment]
> binjitsu is best supported on _**64-bit**_ Ubuntu

You're using a 32-bit release, which we have no way to automate tests for.  I don't have a 32-bit VM.

Use a 64-bit Linux release.
